Vagrant.configure("2") do |config|

  config.vm.box = "eurolinux-vagrant/centos-stream-9"
  config.vm.box_version = "9.0.48"

  config.vm.network "public_network"
  config.vm.network "private_network", ip: "192.168.56.12"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "centos9-web-server"
    vb.cpus = 2
    vb.memory = 1024
  end

  config.vm.provision "shell", inline: <<-SHELL
    yum -y update
    yum -y install httpd unzip curl
    systemctl enable --now httpd
    cd /var/www/html
    rm -rf *
    curl -L -o /tmp/soft_landing.zip https://www.tooplate.com/zip-templates/2106_soft_landing.zip
    unzip -o /tmp/soft_landing.zip -d /tmp/soft_landing
    cp -r /tmp/soft_landing/2106_soft_landing/* /var/www/html/
    chown -R apache:apache /var/www/html
    restorecon -Rv /var/www/html || true
  SHELL
end
