Vagrant.configure("2") do |config|

  config.vm.box = "eurolinux-vagrant/centos-stream-9"
  config.vm.box_version = "9.0.48"

  config.vm.network "public_network"
  config.vm.network "private_network", ip: "192.168.56.12"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "centos9-web-server"
    vb.cpus = 2
    vb.memory = 1024
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo yum install wget httpd unzip -y
    sudo systemctl start httpd
    sudo systemctl enable httpd
    wget https://www.tooplate.com/zip-templates/2106_soft_landing.zip
    unzip -o 2106_soft_landing.zip
    sudo cp -r 2106_soft_landing/* /var/www/html/
    sudo chown -R apache:apache /var/www/html
    sudo systemctl restart httpd
    sudo restorecon -Rv /var/www/html || true
    sudo rm -rf 2106_soft_landing.zip 2106_soft_landing
    
    IP=$(hostname -I | awk '{print $3}')

    echo "======================================"
    echo "Website successfully published!"
    echo "You can access it here: http://$IP"
    echo "======================================"
  SHELL
end
